
FROM java:8-jre

COPY application/target/*-SNAPSHOT.jar /applications/application.jar
COPY gateway/target/*-SNAPSHOT.jar /applications/gateway.jar

ENTRYPOINT ["/bin/sh","-c","java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=test --server.port=8080"]