version: '3'
services:
  mysql:
    image: $MYSQL_IMAGE
    container_name: mysql
    platform: linux/amd64
    restart: always
    env_file:
      - ./data/env/mysql.env
    environment:
    - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      primihub_net:
        ipv4_address: 172.28.1.14

  redis:
    image: $REDIS_IMAGE
    container_name: redis
    platform: linux/amd64
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - nacos
    ports:
      - "6379:6379"
    networks:
      primihub_net:
        ipv4_address: 172.28.1.15

  rabbitmq1:
    image: $RABBITMQ_IMAGE
#    platform: linux/amd64
    container_name: rabbitmq1
    restart: always
    depends_on:
      - redis
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      primihub_net:
        ipv4_address: 172.28.1.16

  rabbitmq2:
    image: $RABBITMQ_IMAGE
#    platform: linux/amd64
    container_name: rabbitmq2
    restart: always
    depends_on:
      - redis
    networks:
      primihub_net:
        ipv4_address: 172.28.1.17

  rabbitmq3:
    image: $RABBITMQ_IMAGE
#    platform: linux/amd64
    container_name: rabbitmq3
    restart: always
    depends_on:
      - redis
    networks:
      primihub_net:
        ipv4_address: 172.28.1.18
  
  nacos:
    image: $NACOS_IMAGE
    container_name: nacos-server
    restart: always
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
      #- ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    environment:
    - TZ=Asia/Shanghai
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    networks:
      primihub_net:
        ipv4_address: 172.28.1.19

  nginx1:
    image: $PRIMIHUB_WEB_MANAGE
    container_name: manage-web1
    restart: always
    volumes:
      - "./config/default1.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30811:80"
#    depends_on:
#      - gateway1
    networks:
      primihub_net:
        ipv4_address: 172.28.1.27
networks:
  primihub_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16